db_uri: postgresql://ae_user:ae_pass@localhost/alphaevolve

llm:
  provider: openai
  model: gpt-4o-mini          # or any model your key can access

evolution:
  population_size: 20
  temperature: 1.5
  max_generations: 30         # keeps PoC run short
  inspiration_count: 6        # number of inspirations to use in each generation

problem:
  entry_script: examples/fibonacci/solution.py
  evaluator:    examples/fibonacci/evaluate.py
