db_uri: sqlite:///alphaevolve.db

experiment:
  label: fib-baseline-v1        # human-readable tag
  notes: "Fibonacci sanity run"
  save_top_k: 5               # number of top programs to save one completion of the experiment

llm:
  provider: openai
  model: gpt-4o-mini          # or any model your key can access

evolution:
  population_size: 20
  temperature: 1.5
  max_generations: 10         # keeps PoC run short
  inspiration_count: 4        # number of inspirations to use in each generation

problem:
  entry_script: examples/fibonacci/solution.py
  evaluator:    examples/fibonacci/evaluate.py
