db_uri: sqlite:///alphaevolve.db

experiment:
  label: fib-baseline-v1        # human-readable tag
  notes: "Fibonacci sanity run"
  save_top_k: 5               # number of top programs to save one completion of the experiment

llm:
  # provider: openai
  # model: gpt-4o-mini          # or any model your key can access
  provider: gemini
  model: gemini-2.5-flash     # or gemini-2.5-pro, etc.

evolution:
  population_size: 40
  temperature: 1.5
  max_generations: 10         # keeps PoC run short
  inspiration_count: 4        # number of inspirations to use in each generation
  max_retries: 3              # number of retries for failed program generation
  evaluation_timeout: 30.0    # timeout in seconds for evaluation runs (0 = no timeout)
  enable_feedback: true       # Enable LLM-generated feedback for successful programs

problem:
  entry_script: examples/fibonacci/solution.py
  evaluator:    examples/fibonacci/evaluate.py
